### ISSUE TITLE
Sending uint64_t numbers over JSON

### ISSUE THREAD

**Issue by ssbanerje** [ipkn/crow#118]
I am trying to use `crow` to make a REST API that will be able to serve 64 bit integer numbers. My code is as follows

```
CROW_ROUTE(app, "/endpoint") ([&]{
    crow::json::wvalue ret;
    uint64_t x = 0x7FFFFFFFFFFFFFFF;
    ret["something"] = x;
    return ret;
  });
```
This seems to typecast the number to a `double` which means that I lose the lower digits of the number. (https://github.com/ipkn/crow/blob/master/include/json.h#L1211-L1217)

Is this how JSON responses are meant to be sent? I don't understand why the typecast happens to double.

**Comment by digitalist** [comment]
It's more like javascript-related problem I guess
http://stackoverflow.com/questions/209869/what-is-the-accepted-way-to-send-64-bit-values-over-json

**Comment by ssbanerje** [comment]
So what would be the acceptable way to send a 64 bit number (say a Unix timestamp) through Crow.

**Comment by digitalist** [comment]
convert with std::to_string(large_number), and send it as string I suppose

**Comment by ssbanerje** [comment]
Thanks. That worked.

**Comment by trungnq97** [comment]
Use `std::to_string()` in `dump_internal ` will help.

```cpp
inline void dump_internal(const wvalue& v, std::string& out)
{
    switch(v.t_)
    {
        case type::Null: out += "null"; break;
        case type::False: out += "false"; break;
        case type::True: out += "true"; break;
        case type::Number: 
            {
                //char outbuf[128];
                //sprintf(outbuf, "%g", v.d);
                //out += outbuf;
                out += std::to_string(v.d);
            }
            break;
        ...
    }
}
```
