### ISSUE TITLE
Accessing void log(std::string message, crow::LogLevel level)

### ISSUE THREAD

**Issue by GP-GPU** [ipkn/crow#120]
Hi,
How do i print a message using the logger without providing my own logger?
e.g. I want to simply use log ("xxx", crow::LogLevel:DEBUG)

thanks,

**Comment by digitalist** [comment]
#include "crow.h"
CROW_LOG_INFO << "message"

other macros (debug, etc) are at the bottom of crow.h

**Comment by GP-GPU** [comment]
Thanks.
