### ISSUE TITLE
send requests from crow

### ISSUE THREAD

**Issue by yaron12n** [ipkn/crow#121]
Can you send get request from crow?

**Comment by digitalist** [comment]
you can send get request, but not from crow per se:
crow knows only about response/request connections. it's a server framework. 
but crow is based on boost::asio, so you just write a middleware with a client (get/post) support

**Comment by digitalist** [comment]
@yaron12n http://cpp-netlib.org/0.11.2/index.html#c-network-library there you go

**Comment by digitalist** [comment]
@yaron12n  eh? maybe it's time to close the issue or report back?

**Comment by jamiebullock** [comment]
See also: https://github.com/chriskohlhoff/urdl also based on boost::asio
