### ISSUE TITLE
crow::json::get_type_str should be inline

### ISSUE THREAD

**Issue by shahmuratov** [ipkn/crow#132]
Hello!
Got problem when included crow.h in multiple files 
```
multiple definition of `crow::json::get_type_str(crow::json::type)'
```
crow::json::get_type_str should be inline.
https://github.com/ipkn/crow/blob/master/include/json.h#L85

**Comment by shahmuratov** [comment]
After submitting found https://github.com/ipkn/crow/pull/113

**Comment by digitalist** [comment]
@shahmuratov then close this issue, please

**Comment by alkalin3** [comment]
This issue is also resolved as of yesterday.
