### ISSUE TITLE
Programatically shutdown a Crow<> instance.

### ISSUE THREAD

**Issue by phaistos** [ipkn/crow#142]
I'd like to be able to shut Crow instances down programmatically as part of a greater thread cleanup scheme for my application. I don't see any members or methods that I can use to do so.

**Comment by sgiurgiu** [comment]
I am not one of the developers, but what I have done is put the app in an unique_ptr which I release when not needed anymore. I agree that it would be nice to not have to do that.

**Comment by ipkn** [comment]
Now you can call `app.stop()`.
