### ISSUE TITLE
how to read and write a JSON with nested objects

### ISSUE THREAD

**Issue by cateof** [ipkn/crow#161]
I am sure that for the experienced crow:: users this is a simple question but this is my first "hello world" project and I want to learn how to read or write nested objects or lists.

For example
```
{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}
```

crow::json::wvalue x;
x["status"] = "available" //this will work for status, ie a string

But how do we read/write a list of objects, like tag or an object like category?

List seem to work like this:
 
crow::json::wvalue x;
 for(int i=0; i < 5; i++) {
    x["message"][i] = i*2;
 }
 return x;

this will return {"message":[0,2,4,6,8]}

But still the question remains for objects. How do I nest an object in the response? 

Thanks for your answer in advance,
Cat

**Comment by airguide** [comment]
@cateof did you manage to solve it?
