### ISSUE TITLE
How can I return crow::json::wvalue from a function?

### ISSUE THREAD

**Issue by cateof** [ipkn/crow#165]
My code is below. I just want to make my code more readable and modular, so I tried to return 
crow::json::wvalue from a fuction (testApi1). My server will only return json, so I would like to have the CROW_ROUTE(s) in a setup function, ie setupHandler, and request from another method to create the json. When I am trying to compile I am getting errors during compile time. 
```
int Handler::setupHandler(crow::SimpleApp& app) {

        CROW_ROUTE(app, "/add_json")
    ([](const crow::request& req){
        crow::json::wvalue res = testApi1();
        return  crow::response{res};
    });

}

crow::json::wvalue Handler::testApi1() {

        crow::json::wvalue r;
        r["message"] = "Hello World";
        r["text"] = 1;

        return r;
}
```
What is the problem? How can I do this?

```
error: ‘this’ was not captured for this lambda function
  crow::json::wvalue res = testApi1();
                                    ^
/home/administrator/lef/betDataGen/JsonHandler.cpp:16:36: error: cannot call member function ‘crow::json::wvalue JsonHandler::testApi1()’ without object
```

**Comment by ipkn** [comment]
The error message describes what you did wrong. You should capture `this` to call `testApi1`. If you are not familiar with lambda, [this link](https://msdn.microsoft.com/en-us/library/dd293608.aspx) will help.

**Comment by cateof** [comment]
Looks like that if I type "([this](const crow::request& req){" instead of "([](const crow::request& req){" the compilation finishes. Do I need "this" or "&this", "*this", etc... ?
