### ISSUE TITLE
How can I get the value of an array?

### ISSUE THREAD

**Issue by cateof** [ipkn/crow#166]
I used the .i() or .s() to take the integer or string value from a field. How can I get the value of an array?

For example from this json request {"name": "crow"} using x["name"].s() I can convert the value to string. Is it possible to get the value of an array?

example: "tiers": [   {"id": 2, "maxValue": 123213},   {"id": 3, "maxValue": 33} ]

Can I load the tiers field in a C++ object easily?

**Comment by Shravan40** [comment]
You can use [json11](https://github.com/dropbox/json11) for this.

```
        string input_error;
        auto x= Json::parse(req.body, input_error);
        if(x == nullptr)
            crow::response(400);
        auto userId = x["user_id"].int_value();
        std::vector<string> senderNumber;
        for(auto& i: x["senderNumber"].array_items()) {
            std::cout << i.dump() << "\n";
        }
```
