### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by acron0** [ipkn/crow#17]
Crow uses the following features that are **still not** supported in MSVC (v120 - Visual Studio 2013):

 - `constexpr`
 - `noexcept`
 - `thread_local` (partial support using __declspec(thread))
 - User defined literals

Any others?

**Comment by ipkn** [comment]
Routing should be reimplemented to support MSVC. I think adding `app.route_dynamic(url)(handler)` is sufficient for it. (Some code might be reusable.)

**Comment by ipkn** [comment]
I finally commit a workaround version 686e5e220b782ef47b5c59271a946bd9603de1d1 for VS2013.

I cannot support CROW_ROUTE, only route_dynamic is.

**Comment by jen6** [comment]
VS 2015 RC support constexpr and noexcept now(have little limitation but works well)
I think crow have to prepare for VS too
http://blogs.msdn.com/b/vcblog/archive/2014/11/17/c-11-14-17-features-in-vs-2015-preview.aspx
