### ISSUE TITLE
JSON 32bit-Integer Improper storage

### ISSUE THREAD

**Issue by fcharlie** [ipkn/crow#176]
Because 32-bit integer type is stored as a double, will result in JSON data returned error, so need to use integer API may not actually use. JSON is actually supports a 32-bit integer.

see code:
https://github.com/ipkn/crow/blob/4e39b23e455e455f1878b3e68d729a1737f3e431/include/crow/json.h#L1247

**Comment by knedlsepp** [comment]
I'm also currently having this problem. I would like to store a UNIX timestamp in a crow::json::wvalue, but since the integer is converted to a double, I get timestamps that look like "1.48573e+09" and thus are unusable. Is there any suggested solution?

**Comment by fcharlie** [comment]
Solution 1: convert timestamp to string 
S 2: write a help class JsonWrite ，set use JsonWrite output string as response body, change Content-Type to json, send response.
