### ISSUE TITLE
Suitable server for production enviroment  (apache/nginx) ?

### ISSUE THREAD

**Issue by Shravan40** [ipkn/crow#214]
I have written my APIs using crow, and for testing purpose i run the server using `./a.out`. But server gets closed whenever any exceptions occurs. Since my code is all set to go into production, I would like to keep running my server irrespective of exception. Please suggest me a way, how to combine it with server like apache, nginx e.t.c

**Comment by jilvin** [comment]
There is no official module to support the production environment. I am currently experimenting to reverse proxy Apache with Crow. Not sure about the performance advantage though.

https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04

This article might be of help to you.

**Comment by jilvin** [comment]
I tested performance of Crow with simple php script served by Apache2.

The performance was 4X downgraded when using Crow.

**Comment by jilvin** [comment]
It's working except a few timeouts recorded while testing with wrk.

**Comment by Shravan40** [comment]
I was able to do it with nginx and it's working pretty well. How can I start the application server (crow server not nginx) as soon as it goes offline due to some reason.

**Comment by DavidUser** [comment]
Can you consider catch all exceptions on entry point?

**Comment by bnlambert** [comment]
I think catching all exceptions at entry point is great. In addition to that consider using docker to restart and run multiple instances of you app.

**Comment by Shravan40** [comment]
@All : I have started catching exception at entry point only. And I am running my application server with [runit](http://smarden.org/runit/).
