### ISSUE TITLE
Is ERROR defined somehwere?

### ISSUE THREAD

**Issue by p-groarke** [ipkn/crow#234]
I'm porting to VS 2017, and pretty much everything is fixed except for the crow::LogLevel enum class (logging.h, line 16). For some reason ERROR is defined, but I can't find any references to it (for ex. in settings.h). Any other idea where it might be defined, or is this a MSVC platform problem?

**Comment by ipkn** [comment]
windows.h defines ERROR so I tried to avoid it with macro. 
old crow source uses ERROR, now it uses Error.

If it is not working, I should fix the macro version check. I will fix it soon.
