### ISSUE TITLE
Catchall / wildcard for routes?

### ISSUE THREAD

**Issue by jamiebullock** [ipkn/crow#236]
Does Crow support any other kinds of substitutions or wildcards?

It would be really useful to do things like:

    CROW_ROUTE(app, "/foo/*")

Matches /foo/bar but not /foo/bar/baz

    CROW_ROUTE(app, "/foo/**")

Matches /foo/bar and /foo/bar/baz recursively

**Comment by ipkn** [comment]
`<str>` matches to `/` (slash) and `<path>` matches to end of route. (But you need to provide arguments for that part).

`/foo/<str>` matches `/foo/bar`, not `/foo/bar/baz`
`/foo/<path>` matches `/foo/bar` and `/foo/bar/baz`

**Comment by jamiebullock** [comment]
Thanks! Whilst I think full glob-style wildcards would be better, this solution is enough for my needs.
