### ISSUE TITLE
Handling database connection and operation in crow

### ISSUE THREAD

**Issue by bnlambert** [ipkn/crow#239]
Crow is a great project. 
I wish to know how database connection and operations  are in Crow apps. Is it done asynchronously or using an ORM?
I need recommendations and examples.

Also I will to know if there are tools to document REST APIs in Crow.
How can we communicate with third party API in Crow app.

The section on middleware is still blank, How can we secure REST APIs in Crow?

Thanks

**Comment by ipkn** [comment]
Crow doesn't support DB access. You need to use another library for it.
If you want to do db jobs in type-safe way, you should check https://github.com/rbock/sqlpp11.

Also crow is just a web server framework, it lacks an API for requesting another web server.

**Comment by bnlambert** [comment]
Any thoughts on how handle middleware in Crow? the documentation seems to be lacking that at the moment. The given link https://github.com/ipkn/crow/issues/239#issuecomment-327389344, is not available.

**Comment by ipkn** [comment]
`middleware` is a plug-in system for `crow` that runs before or after an user handler. You can see the example implementation in middleware.h (CookieParser).

**Comment by bnlambert** [comment]
Please share  a link, I am unable to find it in the branch.

**Comment by bnlambert** [comment]
I found a link here https://github.com/ipkn/crow/blob/master/include/crow/middleware.h . Thanks
