### ISSUE TITLE
Merged crow_all.h doesn't match checked in crow_all.h

### ISSUE THREAD

**Issue by jamiebullock** [ipkn/crow#241]
Running merge_all.py doesn't produce a file identical to the checked in crow_all.h

There are significant diffs

Should I submit a PR with the updated crow_all.h produced by merge_all.py?

**Comment by ipkn** [comment]
I tried to make build tool to output the same result, but maybe it failed.
I will fix it later. 

I want to build crow_all.h from make and make it to be downloaded from GitHub, 
but crow_all.h often pollute PR diff and make it hard to see what changed in the PR.

I'm wondering adding crow_all.h to .gitignore will help it or not.

**Comment by jamiebullock** [comment]
Yeah, I think if crow_all.h can be autogenerated it is best to not commit to the repository and put it in the .gitignore

**Comment by abhishekbsharma** [comment]
@ipkn - make it auto-generate. I can issue a PR for it if you like.

**Comment by ipkn** [comment]
@abhishekbsharma Can you issue the PR? I don't know how to setup for it.

**Comment by ipkn** [comment]
I removed `crow_all.h` from the repository and add it to the release.

https://github.com/ipkn/crow/releases/v0.1
