### ISSUE TITLE
Understanding the crow threading model

### ISSUE THREAD

**Issue by jamiebullock** [ipkn/crow#244]
I'm trying to understand the crow threading model. Can someone confirm if the following is correct:

```
CROW_ROUTE(app, "/")([](){
        return foo();
    });

    app.port(18080).run();
```

If I use the above, then `concurrency_` will be set to `1` (the default) and `foo()` will only ever be called from a single thread at any given time. Therefore `foo()` does not need to be reentrant.

Whereas... If I call `app.port(18080).multithreaded().run()` then I crow will use the value returned by `std::thread::hardware_concurrency()` to set the number of concurrent threads to be used for routing requests and therefore `foo()` could be called from 1 or more threads concurrently and needs to be reentrant.

Is this correct?

**Comment by ipkn** [comment]
Crow creates an io_service per a thread, distribute connections to io_services by the round-robin way and doesn't have work stealing queue now.

It means that, foo can be called by multiple threads concurrently and need to be reentrant.

Note.
By the view point of the connection, it is handled by only one thread.

**Comment by jamiebullock** [comment]
@ipkn does `foo()` need to be reentrant even if `concurrency_ == 1` ?

**Comment by ipkn** [comment]
Yes, it is served by 1 io_service and`foo()` need not be reentrant if `concurrency_ == 1`.

**Comment by jamiebullock** [comment]
Thanks @ipkn this is really helpful
