### ISSUE TITLE
How to manage session in Crow

### ISSUE THREAD

**Issue by bnlambert** [ipkn/crow#248]
Hi
I wish to know if Crow supports session handling out of the box, or how it could be be done.

Thanks

**Comment by ipkn** [comment]
There's no session support in Crow currently.

If you want to implement your server sessions, you can create a session class with a unique string key and send the key to the user with cookie.

**Comment by bnlambert** [comment]
Does this play a role in securing rest api created with crow? 
Such that a unique string is generated for each authenticated user and it is sent with a cookie?

**Comment by ipkn** [comment]
Sorry, I can't understand what you ask. 

If it means that you want to know how you design secured API system, you can check the API key system on Twitter or Facebook to see how they secure their rest API.

**Comment by bnlambert** [comment]
I have been securing rest API using token based authentication often with third party libraries like Oauth2 and jwt. My concern is how it is done in Crow.

Does Crow uses a another library to handle auth or it simply generates unique strings as token for authenticated users?

**Comment by ipkn** [comment]
There's no session support in Crow currently.
