### ISSUE TITLE
Design document for Crow

### ISSUE THREAD

**Issue by abhishekbsharma** [ipkn/crow#249]
@ipkn - I just recently started looking into and using crow. I think it is a really neat micro-framework that you have setup to develop web-services in C++. Although, I was looking a design document or some slide deck that describes the design at a high-level and how you have structure. Otherwise it is hard to navigate through the code. Just wondering if you have design document of such a nature in english.

**Comment by ipkn** [comment]
I'm sorry that currently there's no such document.

This one is best at the moment describing some details of crow: https://docs.google.com/presentation/d/1TwjjYFedVEdLiMiXwbdg3tpYsuwSyrrcqOzPhdfVhNs

**Comment by abhishekbsharma** [comment]
@ipkn - Whatever it is; might be helpful. Why don't u consider adding it temporarily to the documentation. Just as a temp. Something is better than nothing.
