### ISSUE TITLE
Pass variables into the template engine?

### ISSUE THREAD

**Issue by kretash** [ipkn/crow#267]
I'm porting some really really simple code from Flask and I'm wondering how to pass variables?

```python
@app.route('/hello/')
def hello():
    return render_template('hello.html', name="Hello World")
```

But in crow I don't know how to pass that variable into the html. Do I have to parse it in myself?

```cpp
	CROW_ROUTE( app, "/" )([]  #()
	{
		std::ifstream t( "hello.html" );
		std::string website( ( std::istreambuf_iterator<char>( t ) ), std::istreambuf_iterator<char>() );
		std::string hello = "Hello World"; // ???
		return website;
	} );
```

**Comment by kretash** [comment]
It was pretty straight forward to just parse it with boost.

I'm not familiar with crow so I don't know if this is the correct way of doing this.

```cpp
std::string template_variable(std::string& website, std::string name, std::string value ) 
{
	try 
	{
		boost::replace_all(website, "{{ " + name + " }}", value);
	}
	catch(std::exception e)
	{
		std::cerr << e.what();
	}
	return website;
}
```

**Comment by marekfoltyn** [comment]
From https://github.com/ipkn/crow/blob/master/tests/unittest.cpp:

```cpp
TEST(template_basic)
{
    auto t = crow::mustache::compile(R"---(attack of {{name}})---");
    crow::mustache::context ctx;
    ctx["name"] = "killer tomatoes";
    auto result = t.render(ctx);
    // ...
}
```

**Comment by komputronika** [comment]
How to create multidimension array data for mustache?

For example, I want to show list contain name of employees in a mustache template like this:
```
<ul>
    {{#names}}
        <li>{{name}}</li>
    {{/names}}
</ul>
```

I don't know how to prepare array for that. 

Thanks.

**Comment by mrozigor** [comment]
Did you try doing like in the answer above yours? But instead of putting string, assign some type which is iterable (`end()` and `begin()` iterators), as well as accessible via `[]`. Something like:
```
Collection col;
Item i;
i["name"] = "Name";
col.add(i);
crow::mustache::context ctx;
ctx["names"] = col;
```
