### ISSUE TITLE
crow does not compile with latest Visual C++ Compiler

### ISSUE THREAD

**Issue by maxbrueckl** [ipkn/crow#270]
After latest Visual Studio update (15.5.1), crow does not compile for me anymore.

The Visual C++ compiler (14.12.25827) crashes hard at
https://github.com/ipkn/crow/blob/7f3f72441c242836d00ab2109a83baef89c08aaa/include/crow/routing.h#L150

It looks like the compiler cannot handle the amount of black magic that is involved here :smile: 
I assume, this is more likely a compiler bug than a bug in crow.

**Comment by shyblue** [comment]
Also compile error occurred in VS 15.5.2, too

**Comment by Juli1546** [comment]
update boost

**Comment by maxbrueckl** [comment]
Updating boost to version 1.66.0 did not help

**Comment by Juli1546** [comment]
update boost to 1.66.0 and update Visual C++ compiler to 15.5.2,recreate  project.

**Comment by maxbrueckl** [comment]
Just tried it with VS 15.6.2 and it seems to be fine.
