### ISSUE TITLE
Sorry for a noob question

### ISSUE THREAD

**Issue by pgamaster** [ipkn/crow#276]
g++  -std=c++11 main.cpp -o main
In file included from crow.h:7:0,
                 from main.cpp:1:
crow/socket_adaptors.h:6:27: fatal error: crow/settings.h: No such file or directory
 #include "crow/settings.h"
                           ^
compilation terminated.

-------
Just wanted to test it's speed

How can I properly compile this?

**Comment by phonxvzf** [comment]
I encountered this problem too. You need to provide the include directory flag manually.

I added `-Iinclude` to the compiler and it compiled successfully.

**Comment by alen12345** [comment]
Please check also the quickstart guide for basic compilation commands https://github.com/ipkn/crow/wiki/Quickstart 

Moreover you need to the include you need to link against the needed libraries.

Hope this helps in addition to @phonxvzf's answer.
