### ISSUE TITLE
Troubles while compiling on linux

### ISSUE THREAD

**Issue by orzel1244** [ipkn/crow#287]
Hello, I tried to compile the lib on my ubuntu 17.04 by following step from readme, I got some errors:
After "cmake .." https://pastebin.com/uBxT278T
CMakeOutput - https://pastebin.com/5dtgPmbG
CMakeError - https://pastebin.com/5dza5CV8

Cmake version: 3.10.2

I'm sorry because some parts of logs may be in Polish, I hope I'll get help, it could be great if you would provide precompiled libs

**Comment by Rekseto** [comment]
Try to use normal language to that kind of things <3

**Comment by vagaruy** [comment]
You are missing the openssl library. 

I believe they can be installed using the following 
`apt-get install libssl-dev `

**Comment by vagaruy** [comment]
The cmake also has errors finding pthreads. That might not fix the issue

**Comment by vagaruy** [comment]
Maybe try install pthreads too . It should be already installed in Ubuntu though 

`apt-get install libpthread-stubs0-dev`

**Comment by orzel1244** [comment]
I'm getting these errors while trying to install ssl https://pastebin.com/vXCHUfta
Also I had similar problem to install build-essentials
Ubuntu 17.04 xfce

**Comment by orzel1244** [comment]
apt-get update - https://pastebin.com/SAf6vNGt

**Comment by orzel1244** [comment]
It was my fault, that wasn't good idea to do it on 17.04
