### ISSUE TITLE
HTML page is blank

### ISSUE THREAD

**Issue by sugan96** [ipkn/crow#337]
I'm trying to run a HTML file, the program compiles and runs fine but the page is blank when I visit my localhost address. Please help.

<img width="531" alt="Screenshot 2019-03-15 at 3 53 16 PM" src="https://user-images.githubusercontent.com/44352503/54416489-7e0d8000-473a-11e9-919f-caef176c5242.png">

**Comment by mrozigor** [comment]
Do you have "site.html" file in directory you are executing your binary in?

**Comment by sugan96** [comment]
> Do you have "site.html" file in directory you are executing your binary in?

I have it in the same directory as my c files.

**Comment by mrozigor** [comment]
But do you have it in directory you execute binary in? F.e.

- ls
* binary site.html
- ./binary
? Or do you run it from different directory?

**Comment by sugan96** [comment]
> But do you have it in directory you execute binary in? E.g.
> 
> ```
> ls
> -> binary site.html
> ./binary
> ```
> Or do you run it from different directory? (without this html file)

No I have the html file in a separate directory where my project files are not the binary directory. I'm using Xcode here. Also I even tried to put the entire directory path under `load()` but it didn't work

**Comment by tobealion** [comment]
the default file directory is "templates" which is wrote in the file mustache.h at line 516,one way you can solve the issue is to create a directory names templates and put your site.html under, then ./binary

**Comment by mrozigor** [comment]
Can you list directory where your binary is located? Do you run your binary directly from that location?

**Comment by sugan96** [comment]
After searching online I discovered were the default binary folders for Xcode is: `/Users/[my_user]/Library/Developer/Xcode/DerivedData/project_title-[some_random_string]/Build/Products/Debug/project_title`
After placing my html files here, the program works .
