### ISSUE TITLE
Creating Crow server in Server class

### ISSUE THREAD

**Issue by lapleski** [ipkn/crow#376]
Hello.

I want to create Crow server in object oriented paradigm. Something like this:

```
class Server
{
public:
	Server(){
		Application = new crow::SimpleApp;
		Application->route("/", [&](const crow::request& req, crow::response& res) {
		return "index"});
	};
;
private:
	crow::SimpleApp* Application;
```

But I get error with route method of my Application method - "no instance of function template ...". Tell me please, how I supposed to property use route method properly to create route analogically to this:
```
CROW_ROUTE(Application, "/")([](const crow::request& req, crow::response& res) {
        return "index";
        });
```

**Comment by mrozigor** [comment]
`CROW_ROUTE` looks like this -> `#define CROW_ROUTE(app, url) app.route<crow::black_magic::get_parameter_tag(url)>(url)`. Maybe try something like this:
`Application->route<crow::black_magic::get_parameter_tag("/")>("/")([&](const crow::request& req, crow::response& res) {return "index"});`?

**Comment by lapleski** [comment]
On this case I get:
![image](https://user-images.githubusercontent.com/48468561/84567688-fbcb9b80-ad82-11ea-9aed-62e5c7e7c6ef.png)

**Comment by mrozigor** [comment]
Look into code ;) If you pass request and response object, then lambda can't return anything.

**Comment by lapleski** [comment]
@mrozigor thank you 😊
