### ISSUE TITLE
File Parse problem

### ISSUE THREAD

**Issue by saivamsi98** [ipkn/crow#389]
I need to read a json file when a GET request comes. How to do that using std::ostringstream os,can anyone help me with this.....?

``

CROW_ROUTE(app, "/getconfig")
    .methods("GET"_method)
    ([](const crow::request& req) {
               return crow::response(200);
               std::ostringstream os;
               //need to read json file using os
               return crow::response{os.str()};
            });

   app.port(18080)
       .multithreaded()
       .run();

``

**Comment by saivamsi98** [comment]
I have tried this method but it is not displaying any result, any changes I need to do??

``
 CROW_ROUTE(app, "/getconfig/<string>")
    .methods("GET"_method)
    ([](const crow::request& /*req*/, crow::response& res, string filename) {
               //return crow::response(200);
               ifstream inputContent;
               inputContent.open(filename,ifstream::in);
               std::ostringstream os;
               os << inputContent.rdbuf();
               res.write(os.str());
               res.end();
               //os << crow::json::load("o.json");
               //return crow::response{os.str()};
            });
``

**Comment by saivamsi98** [comment]
I tried this way, when I run  this :" curl -X GET http://localhost:18080/getconfig" - It is not displaying the contents in the file and it is throwing an exception. Can anyone explain....?


``

 CROW_ROUTE(app, "/getconfig")
    .methods("GET"_method)
    ([](const crow::request& /*req*/, crow::response& res /*string filename*/) {
               try{
               std::ifstream f("o.json", std::ifstream::binary);
               std::ostringstream os;

               f.seekg (0, f.end);
               long length = f.tellg();
               f.seekg (0);

               char * buffer = new char [length];
               f.read (buffer,length);

               cout << buffer;

               os << buffer;
               f.close();
               res.write(os.str());
               res.end();
               }
               catch(...)
               {
                  cout << "exception" << endl;
               }
               //os << crow::json::load("o.json");
               //return crow::response{os.str()};
            });
``

**Comment by mrozigor** [comment]
May I ask you to use code formatting/displaying code in block? Which exception? It should have message with description of problem. Do you have file `o.json` in the same directory as app?
