### ISSUE TITLE
get_io_service()

### ISSUE THREAD

**Issue by dsimog01** [ipkn/crow#398]
socket_.get_io_service() seems to be deprecated, so I can't run a server using crow.

**Comment by bastien8060** [comment]
Hey, you seem to be talking about file `socket_adaptors.h` right?

**Comment by bastien8060** [comment]
You can add a macro right after the includes: 
```cpp
#if BOOST_VERSION >= 107000
#define GET_IO_SERVICE(s) ((boost::asio::io_context&)(s).get_executor().context())
#else
#define GET_IO_SERVICE(s) ((s).get_io_service())
#endif
```

Then implement it. Replace:
```cpp
        boost::asio::io_service& get_io_service()
        {
            return socket_.get_io_service();
        }
```
with:
```cpp
        boost::asio::io_service& get_io_service()
        {
            return GET_IO_SERVICE(socket_);
        }
```

**Comment by bastien8060** [comment]
Another solution would be to use a fork. Because the maintainer of this repo is inactive, people forked it and took over the development. This one is our MVP: https://github.com/CrowCpp/crow

Everything you need in there, including updates, and fixes. I recommend you use his fixes, updates and work, instead of the code here, which is outdated. The work made by the group CrowCpp is fantastic!

**Comment by dsimog01** [comment]
I am amazed. So fast and so good. The first solution you provided worked.

**Comment by bastien8060** [comment]
Ah, happy for you it worked! 👍

**Comment by dsimog01** [comment]
I get some errors with the repo you told me. Any ideas?
![image](https://user-images.githubusercontent.com/47595345/141601865-9e6fd649-6c65-448f-a0e1-7b232889c134.png)

**Comment by bastien8060** [comment]
Hmm, currently looking into it. Indeed, I can reproduce the same error as you. Will get back, with a solution shortly.

**Comment by The-EDev** [comment]
Hi, CrowCpp/Crow requires you add `#define CROW_MAIN` to the top of your main cpp file. This is to avoid multiple definitions when using multiple source files (We're working to remove the need for it however).

**Comment by dsimog01** [comment]
It works! Thank you!

**Comment by bastien8060** [comment]
> Hi, CrowCpp/Crow requires you add `#define CROW_MAIN` to the top of your main cpp file. This is to avoid multiple definitions when using multiple source files (We're working to remove the need for it however).

You beat me to it :). I had just found https://github.com/CrowCpp/Crow/issues/150
