### ISSUE TITLE
Compilation Error in VS2019 in Windows using vcpkg

### ISSUE THREAD

**Issue by mjjackey** [ipkn/crow#404]
I used vcpkg to install **crow** in VS2019 in Windows, the version is **0.3.4** and installed the dependency **boots** whose version is **1.78.0**. 
I used `#include "crow_all.h"`, but the error pops up 
![image](https://user-images.githubusercontent.com/14541043/155088940-7efe6fe1-8e5f-4043-9bbe-f37004a465d1.png)
When I used `#include  "crow.h"`, the linked errors appear.
<img width="1448" alt="error" src="https://user-images.githubusercontent.com/14541043/155090692-277073a5-d107-4b4f-b81f-bbd4714126bb.PNG">
Could someone help me？

**Comment by The-EDev** [comment]
I believe you posted in the wrong repository, you're looking for https://github.com/CrowCpp/Crow.

**Comment by mjjackey** [comment]
> I believe you posted in the wrong repository, you're looking for https://github.com/CrowCpp/Crow.

Thank you for your reply!
What's the difference between the two repositories?

**Comment by The-EDev** [comment]
This one hasn't been active since 2017, and considering the main developer's activity over the past few years (being barely there since 2016 and not there at all since 2020) it doesn't seem like it ever will be active again.

 As explained in #387, [CrowCpp/Crow](https://github.com/CrowCpp/Crow) is a community effort to maintain, bugfix, and build up the project.

**Comment by mjjackey** [comment]
> This one hasn't been active since 2017, and considering the main developer's activity over the past few years (being barely there since 2016 and not there at all since 2020) it doesn't seem like it ever will be active again.
> 
> As explained in #387, [CrowCpp/Crow](https://github.com/CrowCpp/Crow) is a community effort to maintain, bugfix, and build up the project. We've added so much over the past year and half that I'd be reluctant to compare the 2 projects

Thank you for your reply!
