### ISSUE TITLE
Server hits a wall at ~16384 connections

### ISSUE THREAD

**Issue by gamache** [ipkn/crow#54]
Hi there! Pardon me if I am making a simple mistake, but I have been benchmarking a Crow server using Apache Bench (`ab`), and I seem to be predictably hitting a wall at slightly under 16384 connections (the number varies between 16340 and 16360, always just shy of 2**14).  The server stays locked up for tens of seconds.  I tested on a MacBook Pro using each of g++ 4.9 and clang++ 6.0.

Pasted below is a minimal test case and `ab` output.  Any ideas?

Thanks! --pete

```bash
$ cat trivial-server.cpp
#include "crow_all.h"

int main() {
  crow::SimpleApp app;

  CROW_ROUTE(app, "/")
  ([](){
    return crow::response(200);
  });

  app.port(8080).multithreaded().run();
}

$ clang++ -o trivial-server -std=c++1y -lboost_system trivial-server.cpp

$ ./trivial-server 2>/dev/null &
[1] 2449

$ ab -n 20000 http://127.0.0.1:8080/
This is ApacheBench, Version 2.3 <$Revision: 1554214 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_socket_recv: Operation timed out (60)
Total of 16358 requests completed
```

**Comment by ipkn** [comment]
I did the same test quickly at my ubuntu server and it doesn't have any problems at serving 20000 requests. I will test again with my MacBook Air soon.

**Comment by ipkn** [comment]
I think this url explains what happened. 

http://stackoverflow.com/questions/1216267/ab-program-freezes-after-lots-of-requests-why

How about adding `-k` option to use keep-alive or testing with other tools like `wrk`?

**Comment by gamache** [comment]
That is exactly it! Sorry to waste your time, and thanks for the pointer.
