### ISSUE TITLE
Can't define same route for differents methods

### ISSUE THREAD

**Issue by agonist** [ipkn/crow#57]
Hi, I started to test crow, works fine but when I try to do the following  :  

````
 
    CROW_ROUTE(app,"/db/<string>")
    .methods("GET"_method)
    ([](string dbName){
       return crow::response(200);
    });

    CROW_ROUTE(app,"/db/<string>")
    .methods("PUT"_method)
    ([](string dbName){
       return crow::response(200);
    });

    CROW_ROUTE(app,"/db/<string>")
    .methods("DELETE"_method)
    ([](string dbName){
       return crow::response(200);
    });
````

it throw an exception "handler already exists for /db/<string>"

Why I can't use the same route but for differents methods ? Is this normal ?

Thank's

**Comment by ipkn** [comment]
No, it's a bug. I will fix this soon. 

Current implementation only allows one handler for a route. If you want a quick workaround, you can put all handlers for different method in one route.
```
CROW_ROUTE(app,"/db/<string>")
.methods("GET"_method | "PUT"method | "DELETE"_method)
([](const request& req, string dbName) {
  if (req.method == "GET"_method) 
    ...
});
```

**Comment by agonist** [comment]
seems to not working 

In file included from main.cpp:1:
./server.hpp:53:27: error: invalid operands to binary expression ('crow::HTTPMethod' and 'crow::HTTPMethod')
    .methods("GET"_method | "PUT"_method | "DELETE"_method)
             ~~~~~~~~~~~~ ^ ~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/bitset:1045:1: note: candidate template ignored:
      could not match 'bitset<_Size>' against 'crow::HTTPMethod'
operator|(const bitset<_Size>& __x, const bitset<_Size>& __y) _NOEXCEPT

**Comment by ipkn** [comment]
Sorry again, I'm late.

You should write like this:
```
.methods("GET"_method, "PUT"_method, "DELETE"_method)
```

**Comment by agonist** [comment]
Works great thank's !

Just to say, I use crow for a school project, and after long time searching, crow apear to be the best and simplier lib to do a simple web service. Great work !
