### ISSUE TITLE
Check if json request parameter exist

### ISSUE THREAD

**Issue by KnutFr** [ipkn/crow#63]
Hi,
I use crow for a basic web-service to manage DB, and I would like to know if it's possible to test existence of a parameters in request body. 

For example, I have this code:
```
    	else  if (req.method == "POST"_method) 
		{
			auto x = crow::json::load(req.body);
	        if (!x)
	        	return crow::response(400, BADREQUEST);
		    if (!x["db"]) //Parameter key to test
			    return crow::response(404, DBNOTFOUND);
         }
```

But it's always return 500 Internal server error with this message in log:  An uncaught exception occurred: cannot find key. 

Is it possible to test if parameter key exist ? 

Thanks

**Comment by sivachandran** [comment]
You can use x.has("db") to check whether it exist.

**Comment by KnutFr** [comment]
It works great for me, thanks
