### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by wenzhenl** [ipkn/crow#69]
I am not sure whether this is caused by crow, when I use crow.h sometimes my program takes 100% CPU and couldn't respond to requests, but this doesn't happen when I use crow_all.h, previously you were fixing the bug in http_parser_merged and but this bug is not fixed in crow_all.h, I am wondering whether some bug was introduced during that fix.

**Comment by ipkn** [comment]
I fixed a multithread related bug at 5b72a099736faca57ff2e2906bb1912ed29498d0.

Can you test again with the new version?
