### ISSUE TITLE
Issue with pathes & including css + javascript?

### ISSUE THREAD

**Issue by g12mcgov** [ipkn/crow#74]
I'm trying to build a simple web app that's structured like this:

```
main.cpp
public/
    css/
        style.css
    img/
        test.png
    js/
        test.js
    templates/
        about.html
        blog.html
        index.html
vendor/
    crow_all.h
    mustache.h
    mustache.cpp
main.dSYM
makefile
main
```

However, I can't get the imports to work for the life of me. For example, I've tried several variations of the path within this `href` tag, but it constantly returns a `404` error when locating the style.css file. I've loaded this project into Apache, and it works totally fine. Any ideas?

```html
<link rel="stylesheet" type="text/css" href="./public/css/style.css"/>
```

Main.cpp: 

```c++
int main()
{
    crow::SimpleApp app;
    crow::mustache::set_base(".");

    CROW_ROUTE(app, "/")
    ([](){
        crow::mustache::context ctx;
        return crow::mustache::load("public/templates/index.html").render();
    });

    CROW_ROUTE(app, "/about")
    ([](){
        return crow::mustache::load("public/templates/about.html").render();;
    });

    CROW_ROUTE(app, "/github")
    ([](){
        return crow::mustache::load("").render();;
    });
}
```

**Comment by acron0** [comment]
If you log your current working directory, what does it show?

**Comment by g12mcgov** [comment]
Yes, the current working directory is:

```Current working dir: /Users/grantmcgovern/Sites/PersonalSiteV2```

**Comment by acron0** [comment]
Oh, I'm sorry, I skimmed your first post. So this isn't to do with the mustache templates? Crow does not have a static file support, built in. I recommend you look into writing some middleware to handle statics, or directly into the routes for now.

Pseudo example for a route:

    CROW_ROUTE(app, "/static/<string>")
    ([](std::string path){
        if(path_exists(path)) {
           crow::response r(read_all_of_file(path));
           r.add_header("Content-Type", pick_content_type(path));
           return r;
        }
        else {
           return 404;
        }
    });

**Comment by g12mcgov** [comment]
Gotcha, that's what I feared. Thanks a lot though, and time pending, maybe I'll write some middleware.

**Comment by digitalist** [comment]
i'd suggest taking look here https://gist.github.com/mpapierski/7075548
and implementing static files through "do_write_sendfile" or something like this, that's the way nginx does this, middleware seems like overhead

**Comment by digitalist** [comment]
it works, btw, will pull request later.

**Comment by hnfsrj** [comment]
Static files like css and js need to be in static folder for Crow to automatically be able to find them. You then change the href of the static file to "/static/style.css" or "/static/main.js". This worked for me
