### ISSUE TITLE
Cannot build on mac OS X Yosemite

### ISSUE THREAD

**Issue by jcbritobr** [ipkn/crow#78]
*Build Log*
-
[ 11%] Built target amalgamation
[ 22%] Built target example
[ 33%] Built target example_chat
[ 44%] Built target example_chat_copy
[ 55%] Built target example_copy
[ 66%] Built target example_with_all
[ 77%] Building CXX object tests/CMakeFiles/unittest.dir/unittest.cpp.o
/Users/julio/Projects/crow/tests/unittest.cpp:936:27: error: call to 'move' is
      ambiguous
        last_url_params = move(req.url_params);
                          ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1603:1: note: 
      candidate function [with _Tp = const crow::query_string &]
move(_Tp&& __t) _NOEXCEPT
^
/usr/local/include/boost/move/utility_core.hpp:191:77: note: candidate function
      [with T = const crow::query_string &]
  ...inline typename ::boost::move_detail::remove_reference<T>::type && move(...
                                                                        ^
1 error generated.
make[2]: *** [tests/CMakeFiles/unittest.dir/unittest.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/unittest.dir/all] Error 2
make: *** [all] Error 2

System Specifications
-
*Boost version: 1.58.0*

*uname -a
Darwin MacBook-Pro-de-Julio-Cesar-Brito-Gardona.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86*

**Comment by ChaoMai** [comment]
take a look at #77 , should be helpful for you :)

**Comment by jcbritobr** [comment]
Thanks, Chao Mai

It helps. Fix it here.

At.

Júlio C. Brito Gardona
